# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=200)),
                ('sdetails', models.TextField()),
                ('slocation', models.CharField(max_length=200)),
            ],
        ),
    ]
