# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='sratings',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
