# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edup', '0003_remove_school_sdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='simage',
            field=models.ImageField(default=0, upload_to='static/searchicon.png', verbose_name='img'),
            preserve_default=False,
        ),
    ]
